Das Qwt Handbuch
================
Andreas Nicolai <andreas.nicolai@gmx.de>
v1.0.0, Mai 2025
:Author Initials: AN
:toc: left
:toclevels: 3
:icons: font
:imagesdir: ../images
:numbered:
:website: https://ghorwin.github.io/QwtBook
:source-highlighter: rouge
:rouge-style: custom
:title-page:
:stylesdir: ../css
:stylesheet: roboto_ubuntu.css
:toc-title: Inhaltsverzeichnis
:caution-caption: Achtung
:example-caption: Beispiel
:figure-caption: Abbildung
:table-caption: Tabelle
:section-refsig: Kapitel
:xrefstyle: short

:numbered!:

## Über dieses Handbuch

Dieses Projekt ergänzt die API-Dokumentation zur Qwt-Bibliothek und bietet sowas wie ein Programmiererhandbuch mit vielen Details zu den Internas der Bibliothek. Der Fokus liegt aber ganz klar auf der `QwtPlot` Diagrammkomponente.  
Das ist übrigends schon die 2. Auflage (komplett neu überarbeitet), weil es zum Zeitpunkt der ersten Ausgabe noch kein tolles AsciiDoc gab und ich irgendwie beim Textschreiben hängengeblieben bin. 

Die Texte und Bilder stehen unter der Creative-Commons BY-NC Lizenz (siehe Lizenztext im Qwt Handbuch Repository https://github.com/ghorwin/QwtBook[https://github.com/ghorwin/QwtBook]), können also frei verwendet, modifiziert und angepasst werden, aber bitte nicht publiziert oder zum Training von kommerziellen KI-Systemen benutzt werden.
Alle Quelltextbeispiele, sowohl im Text, als auch in den herunterladbaren Tutorial/Beispiel-Quelltextarchiven, stehen unter der MIT-Lizenz und können damit in open-source wie auch kommerziellen Projekten genutzt werden.

[TIP]
====
Häufig wird das `QwtPlot` ja benutzt, um ein eigenes Postprozessing oder Visualisierungstool zu schreiben. Vielleicht lohnt sich hier der Blick auf das kostenfreie _PostProc 2_, welches wir an der TU Dresden entwickelt haben und das intern ein angepasstes und erweitertes `QwtPlot` verwendet. Das Programm ist spezialisiert auf die Visualisierung von dynamischer Simulationsergebnissen und Messdaten/Zeitreihen und man kann da einen guten Eindruck davon bekommen, was mit `QwtPlot` alles machbar ist. _Postproc 2_ wird weiter aktiv gepflegt und kann hier heruntergeladen werden: https://bauklimatik-dresden.de/software/postproc2/[https://bauklimatik-dresden.de/software/postproc2/].
====

Viel Spaß bei der Lektüre - und falls noch Inhalte fehlen, einfach Geduld haben und später wiederkommen (oder im Github-Repo ein Issue anlegen). Und schaut Euch vielleicht auch meine anderen Tutorials unter https://schneggenport.de[https://schneggenport.de] an!

-- Andreas Nicolai

:numbered:

include::Introduction.adoc[leveloffset=+1]
include::BasicTutorial.adoc[leveloffset=+1]
include::QwtWidgets.adoc[leveloffset=+1]
include::LineCurves.adoc[leveloffset=+1]
include::Legend.adoc[leveloffset=+1]
include::Marker.adoc[leveloffset=+1]
include::Axes.adoc[leveloffset=+1]
include::Text.adoc[leveloffset=+1]
include::Zoomer.adoc[leveloffset=+1]

include::Styling.adoc[leveloffset=+1]
include::Print.adoc[leveloffset=+1]
include::Fortgeschrittenes.adoc[leveloffset=+1]

include::Building.adoc[leveloffset=+1]

## Über den Autor

... später, siehe https://schneggenport.de[https://schneggenport.de]
