Das Qwt Handbuch
================
Andreas Nicolai <andreas.nicolai@gmx.de>
v1.0.0, Mai 2025
:Author Initials: AN
:toc: left
:toclevels: 3
:icons: font
:imagesdir: ../images
:numbered:
:website: https://ghorwin.github.io/QwtBook
:source-highlighter: rouge
:rouge-style: custom
:title-page:
:stylesdir: ../css
:stylesheet: roboto_ubuntu.css
:toc-title: Inhaltsverzeichnis
:caution-caption: Achtung
:example-caption: Beispiel
:figure-caption: Abbildung
:table-caption: Tabelle
:section-refsig: Kapitel
:xrefstyle: short

:numbered!:

## Über dieses Handbuch

Dieses Projekt ergänzt die Dokumentation zur Qwt-Bibliothek und bietet sowas wie ein Programmiererhandbuch mit vielen Details zu den Internas. Der Fokus liegt aber ganz klar auf der `QwtPlot` Diagrammkomponente. 

Das Buch schreibe ich in Deutsch, aber Dank der modernen Webseiten-Übersetzer kann man das bestimmt auch locker in vielen anderen Sprachen lesen :-)

Die Texte, Bilder und Beispielquelltexte stehen unter der BDS-3 Lizenz (siehe https://github.com/ghorwin/QwtBook[Qwt Handbuch Repository]). Wäre natürlich cool, 
wenn der eine oder andere hier etwas beisteuern würde. Das ist übrigends schon die 2. Auflage (komplett neu überarbeitet), weil es zum Zeitpunkt der ersten Ausgabe noch kein tolles AsciiDoc gab und ich irgendwie beim Textschreiben hängengeblieben bin. 

Viel Spaß bei der Lektüre - und falls noch Inhalte fehlen, einfach Geduld haben und später wiederkommen (oder im Github-Repo ein Issue anlegen).

-- Andreas Nicolai

:numbered:

include::Introduction.adoc[leveloffset=+1]
include::BasicTutorial.adoc[leveloffset=+1]
include::LineCurves.adoc[leveloffset=+1]
include::Legend.adoc[leveloffset=+1]
include::Styling.adoc[leveloffset=+1]
include::Building.adoc[leveloffset=+1]
include::Print.adoc[leveloffset=+1]

