:imagesdir: images

[[sec:building]]
# Download/Installation/Erstellung der Qwt Bibliothek

## Download fertiger Pakete

### Linux

Unter Linux kann man auf die Pakete des Paketmanagers zurückgreifen. 

#### Debian/Ubuntu

```sh
# Paket mit Headern für die Entwicklung
sudo apt install libqwt-qt5-dev 
```

Headerdatei-Pfad:  `/usr/include/qwt`



[[sec:buildingFromSource]]
## Erstellung aus dem Quelltext

### Windows

- Release `qwt-6.3.0.zip`  herunterladen und entpacken.
- Datei `qwtconfig.pri` bearbeiten und Optionen ein-/ausschalten
- Kommandozeile mit Qt Umgebungsvariablen öffnen: Startmenu -> Qt 5.15.2 (MinGW 8.1.0 64-bit)
- Ins Verzeichnis mit der `qwt.pro` wechseln

### Windows - MinGW32

Es wird eine MinGW32 Installation mit `mingw32-make` im PATH erwartet.

```bat
:: Makefile erstellen
qmake qwt.pro
:: Bibliothek und Plugin/Beispiele bauen
mingw32-make -j8
:: Biblithek installieren
mingw32-make install
``` 
[TIP]
====
Die `-j8` sind für das parallele Bauen auf 8 CPUs.
====


Sofern nicht in der Datei `qwtconfig.pri` ein anderer Installationspräfix in der Variable `QWT_INSTALL_PREFIX` eingestellt wurde, ist die Bibliothek nun unter `c:\Qwt-6.3.0` installiert:

  c:\Qwt-6.3.0\include  - Header-Dateien
  c:\Qwt-6.3.0\lib      - Bibliothek/DLLs
  c:\Qwt-6.3.0\doc\html - API Dokumentation (`index.html` in diesem Verzeichnis öffnen)




### Linux/Mac

[[sec:designerPlugins]]
## Qt Designer Plugins

... wie erstellt man die Designerplugins und bekommt die in die Komponentenpalette...

## Verwendung des Plots in eigenen Programmen

### Windows

### Linux/Mac

